/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package user;

/**
 *
 * @author icbt1A
 */
public class MainUI extends javax.swing.JFrame {
    private String userRole;

    /**
     * Creates new form MainUI
     */
    public MainUI(String role) {
        initComponents();
        setLocationRelativeTo(this);
        this.userRole = role;
        checkRolePermissions();
    }
    
    private void checkRolePermissions() {
        if (!"manager".equals(userRole)) {
            jMenu3.setEnabled(false); // Disable "Edit" menu
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuPatient = new javax.swing.JMenuItem();
        mnuBooking = new javax.swing.JMenuItem();
        mnuConsultant = new javax.swing.JMenuItem();
        mnuClose = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuNewUser = new javax.swing.JMenuItem();
        mnuDeleteUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        mnuPatient.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuPatient.setText("Patient");
        mnuPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPatientActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPatient);

        mnuBooking.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mnuBooking.setText("Booking");
        jMenu1.add(mnuBooking);

        mnuConsultant.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mnuConsultant.setText("Consultant");
        mnuConsultant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultantActionPerformed(evt);
            }
        });
        jMenu1.add(mnuConsultant);

        mnuClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnuClose.setText("Close");
        mnuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCloseActionPerformed(evt);
            }
        });
        jMenu1.add(mnuClose);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Edit");

        mnuNewUser.setText("New User");
        jMenu3.add(mnuNewUser);

        mnuDeleteUser.setText("Delete user");
        jMenu3.add(mnuDeleteUser);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuCloseActionPerformed

    private void mnuPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPatientActionPerformed
        // TODO add your handling code here:
        PatientUI pUI=new PatientUI();
        pUI.setVisible(true);
    }//GEN-LAST:event_mnuPatientActionPerformed

    private void mnuConsultantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultantActionPerformed
        // TODO add your handling code here:
        ConsultantUI cUI=new ConsultantUI();
        cUI.setVisible(true);
    }//GEN-LAST:event_mnuConsultantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new MainUI("manager").setVisible(true); // Provide a default role
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuBooking;
    private javax.swing.JMenuItem mnuClose;
    private javax.swing.JMenuItem mnuConsultant;
    private javax.swing.JMenuItem mnuDeleteUser;
    private javax.swing.JMenuItem mnuNewUser;
    private javax.swing.JMenuItem mnuPatient;
    // End of variables declaration//GEN-END:variables
}
